### ISSUE TITLE
quick reference [A-z]

### ISSUE THREAD

**Issue by w-kuhn** [jonmagic/scriptular#51]
Hi there! Thanks so much for maintaining scriptular. Great resource. 

I noticed something in the quick reference text that perhaps could be misleading for people who are learning regex.

`[A-z] | Match any character from uppercase A to lowercase z`

While this character class does match all upper and lowercase alphabetic characters, it also matches 6 characters that fall between Z and a, which may not be intended. Do you think this would be a valuable change to the reference text (to instead suggest something like `[A-Za-z]`)? If so, I'd be glad to do a PR for that. Thank you.
![regexaz](https://user-images.githubusercontent.com/26445654/46582439-4fadab00-ca0c-11e8-9b13-5695addb64d1.jpg)

**Comment by jonmagic** [comment]
Great suggestion! Would you mind opening a PR with the change?

**Comment by w-kuhn** [comment]
PR opened. Thanks so much for considering.

**Comment by jonmagic** [comment]
Shipped and added you to the contributors list, thanks so much :metal:
